Repository BlockSigner/cove, pull requests merged in 2020-03, with the labels that each got.

#298 [MRG] feat(Partners): Add new partners page in german
  site/config.yaml
  site/content/english/image/partner/partner-elca-132w.jpg
  site/content/english/image/partner/partner-elca-132w.webp
  site/content/english/image/partner/partner-elca-66w.jpg
  site/content/english/image/partner/partner-elca-66w.webp
  site/content/english/image/partner/partner-expert-suisse-118w.jpg
  site/content/english/image/partner/partner-expert-suisse-118w.webp
  site/content/english/image/partner/partner-expert-suisse-236w.jpg
  site/content/english/image/partner/partner-expert-suisse-236w.webp
  site/content/english/image/partner/partner-fidentity-118w.jpg
  site/content/english/image/partner/partner-fidentity-118w.webp
  site/content/english/image/partner/partner-fidentity-236w.jpg
  site/content/english/image/partner/partner-fidentity-236w.webp
  site/content/english/image/partner/partner-procivis-118w.jpg
  site/content/english/image/partner/partner-procivis-118w.webp
  site/content/english/image/partner/partner-procivis-236w.jpg
  site/content/english/image/partner/partner-procivis-236w.webp
  site/content/english/image/partner/partner-sav-fsa-110w.jpg
  site/content/english/image/partner/partner-sav-fsa-110w.webp
  site/content/english/image/partner/partner-sav-fsa-220w.jpg
  site/content/english/image/partner/partner-sav-fsa-220w.webp
  site/content/english/image/partner/partner-softcom-160w.jpg
  site/content/english/image/partner/partner-softcom-160w.webp
  site/content/english/image/partner/partner-softcom-80w.jpg
  site/content/english/image/partner/partner-softcom-80w.webp
  site/content/english/image/partner/partner-spectas-152w.jpg
  site/content/english/image/partner/partner-spectas-152w.webp
  site/content/english/image/partner/partner-spectas-76w.jpg
  site/content/english/image/partner/partner-spectas-76w.webp
  site/content/english/image/partner/partner-swiss-made-100w.jpg
  site/content/english/image/partner/partner-swiss-made-100w.webp
  site/content/english/image/partner/partner-swiss-made-200w.jpg
  site/content/english/image/partner/partner-swiss-made-200w.webp
  site/content/english/image/partner/partner-swisscom-146w.jpg
  site/content/english/image/partner/partner-swisscom-146w.webp
  site/content/english/image/partner/partner-swisscom-73w.jpg
  site/content/english/image/partner/partner-swisscom-73w.webp
  site/content/english/image/partner/partner-vshn-154w.jpg
  site/content/english/image/partner/partner-vshn-154w.webp
  site/content/english/image/partner/partner-vshn-77w.jpg
  site/content/english/image/partner/partner-vshn-77w.webp
  site/content/english/image/partners-1120w.jpg
  site/content/english/image/partners-1120w.webp
  site/content/english/image/partners-560w.jpg
  site/content/english/image/partners-560w.webp
  site/content/english/og/og-skribble.partners.jpg
  site/content/english/partners.md
  site/content/french/integration.md
  site/content/french/partners.md
  site/content/german/integration.md
  site/content/german/partners.md
  site/layouts/shortcodes/partner.html
  site/layouts/shortcodes/partners.html
  src/css/imports/mixins.scss
  src/css/imports/partner.scss
  src/css/main.scss
Labels: tested: OK

#305 [MRG] update(partners): set better spectas title
  site/content/english/partners.md
  site/content/french/partners.md
  site/content/german/partners.md
Labels: tested: OK

#317 [MRG] update(delegated@2x.jpg): add image for delegation mails
  site/static/email/delegated@2x.jpg
Labels: w/o testing

#319 [MRG] fix(French): Add missing translation
  site/content/french/identification/aes-for-business/index.md
Labels: w/o testing

#321 [MRG] feat(Open graph): Add current permalink as og url
  site/layouts/_default/baseof.html
Labels: w/o testing

#322 [MRG] fix(A4B): add proper meta-title and meta-description contents
  site/content/english/identification/aes-for-business/index.md
  site/content/french/identification/aes-for-business/index.md
  site/content/german/identifikation/aes-for-business/index.md
Labels: Deploy ASAP!, w/o testing

#320 [MRG] new-features: assign signer and invite new signer
  site/content/english/_index.md
  site/content/english/features-business.md
  site/content/english/features.md
  site/content/french/_index.md
  site/content/french/features-business.md
  site/content/french/features.md
  site/content/german/_index.md
  site/content/german/features-business.md
  site/content/german/features.md
  site/static/features/additional-signer.svg
  site/static/features/assign-signer.svg
Labels: w/o testing

#307 [MRG] feat(IE): Add fallback page to redirect to from wave
  site/content/english/image/ie-fallback-visual-565w.jpg
  site/content/english/upgrade-your-browser.md
  site/layouts/shortcodes/browser-list.html
  site/layouts/shortcodes/picture.html
  site/layouts/shortcodes/side-by-side.html
  site/static/chrome.png
  site/static/firefox.png
  site/static/microsoft-edge.png
  site/static/robots.txt
  src/css/imports/browser-list.scss
  src/css/main.scss
Labels: tested: OK
