Repository BlockSigner/cove, pull requests merged in 2020-05, with the labels that each got.

#347 [MRG] Business-features update
  site/content/english/features-business.md
  site/content/french/features-business.md
  site/content/german/features-business.md
Labels: w/o testing

#349 [MRG] update(status.txt): add downtime banner
  site/static/status.txt
Labels: w/o testing

#350 [MRG] update(status.txt): move to proper location
  site/static/my.skribble/status.txt
  site/static/status.txt
Labels: w/o testing

#351 [MRG] update(status.txt): remove html as it's not supported
  site/static/my.skribble/status.txt
Labels: w/o testing

#352 [MRG] docs(status.txt): Add instructions on how to change status in WAVE
  README.md
Labels: w/o testing

#353 [MRG] docs(toc): Add toc for newly introduced section
  README.md
Labels: w/o testing

#354 [MRG] update(status.txt): remove banner again
  site/static/my.skribble/status.txt
Labels: w/o testing

#336 [MRG] Teaser for video-ident
  site/content/english/_index.md
  site/content/english/enable-qes.md
  site/content/english/hr.md
  site/content/english/identification.md
  site/content/english/image/aes-for-biz-home-id-280w.jpg
  site/content/english/image/aes-for-biz-home-id-280w.webp
  site/content/english/image/aes-for-biz-home-id-560w.jpg
  site/content/english/image/aes-for-biz-home-id-560w.webp
  site/content/english/image/video-ident-250w.jpg
  site/content/english/image/video-ident-250w.webp
  site/content/english/image/video-ident-500w.jpg
  site/content/english/image/video-ident-500w.webp
  site/content/english/increase-legal-weight.md
  site/content/english/lawyer.md
  site/content/english/signaturestandards.md
  site/content/french/_index.md
  site/content/french/enable-qes.md
  site/content/french/hr.md
  site/content/french/identification.md
  site/content/french/increase-legal-weight.md
  site/content/french/lawyer.md
  site/content/french/signaturestandards.md
  site/content/german/_index.md
  site/content/german/enable-qes.md
  site/content/german/hr.md
  site/content/german/identification.md
  site/content/german/increase-legal-weight.md
  site/content/german/lawyer.md
  site/content/german/signaturestandards.md
Labels: tested: OK

#355 [MRG] CTA increase legal weight
  site/config.yaml
Labels: w/o testing

#337 [MRG] New testimonials on features and integration
  site/content/english/features-business.md
  site/content/english/features.md
  site/content/english/image/testimonial/descartesfinance-150w.png
  site/content/english/image/testimonial/descartesfinance-300w.png
  site/content/english/image/testimonial/kantonschaffhausen-150w.png
  site/content/english/image/testimonial/kantonschaffhausen-300w.png
  site/content/english/integration.md
  site/content/french/features-business.md
  site/content/french/features.md
  site/content/french/integration.md
  site/content/german/features-business.md
  site/content/german/features.md
  site/content/german/integration.md
  site/layouts/shortcodes/features-container.html
  site/layouts/shortcodes/features-item.html
  site/static/features/archive-auto-delation.svg
  src/css/imports/features-container.scss
  src/css/imports/features-item.scss
Labels: tested: OK

#357 [MRG] Soraya new team member
  site/content/english/team.md
  site/content/english/team/soraya-kohler-l.jpg
  site/content/english/team/soraya-kohler-l.webp
  site/content/english/team/soraya-kohler-l@2x.jpg
  site/content/english/team/soraya-kohler-l@2x.webp
  site/content/french/team.md
  site/content/german/team.md
Labels: w/o testing

#356 [MRG] update: CTA identification and enable-qes
  site/content/english/enable-qes.md
  site/content/english/identification.md
  site/content/french/enable-qes.md
  site/content/french/identification.md
  site/content/german/enable-qes.md
  site/content/german/identification.md
Labels: w/o testing

#359 [MRG] Text corrections
  site/content/english/enable-qes.md
  site/content/english/price.md
  site/content/english/team.md
  site/content/french/enable-qes.md
  site/content/french/price.md
  site/content/french/team.md
  site/content/german/enable-qes.md
  site/content/german/price.md
  site/content/german/team.md
Labels: w/o testing

#346 [MRG] SES adaption
  site/content/english/_index.md
  site/content/english/hr.md
  site/content/english/identification.md
  site/content/english/lawyer.md
  site/content/french/_index.md
  site/content/french/hr.md
  site/content/french/identification.md
  site/content/french/lawyer.md
  site/content/german/_index.md
  site/content/german/hr.md
  site/content/german/identification.md
  site/content/german/lawyer.md
Labels: tested: OK

#358 [MRG] Jevgenija new team member
  site/content/english/team.md
  site/content/english/team/jevgenija-litvina-l.jpg
  site/content/english/team/jevgenija-litvina-l.webp
  site/content/english/team/jevgenija-litvina-l@2x.jpg
  site/content/english/team/jevgenija-litvina-l@2x.webp
  site/content/french/team.md
  site/content/german/team.md
Labels: w/o testing

#360 [MRG] 4 new sales-jobs
  netlify.toml
  site/content/english/careers.md
  site/content/english/careers/account-executive-ch.md
  site/content/english/careers/account-executive.md
  site/content/english/careers/country-manager-de.md
  site/content/english/careers/customer-success-manager-de.md
  site/content/english/careers/sales-consultant.md
  site/content/english/careers/sales-development-representative.md
  site/content/english/careers/sales-manager-de.md
  site/content/english/careers/success-manager.md
  site/content/french/careers.md
  site/content/french/careers/account-executive-ch.md
  site/content/french/careers/account-executive.md
  site/content/french/careers/country-manager-de.md
  site/content/french/careers/customer-success-manager-de.md
  site/content/french/careers/sales-consultant.md
  site/content/french/careers/sales-development-representative.md
  site/content/french/careers/sales-manager-de.md
  site/content/french/careers/success-manager.md
  site/content/german/careers.md
  site/content/german/careers/account-executive-ch.md
  site/content/german/careers/account-executive.md
  site/content/german/careers/country-manager-de.md
  site/content/german/careers/customer-success-manager-de.md
  site/content/german/careers/sales-consultant.md
  site/content/german/careers/sales-development-representative.md
  site/content/german/careers/sales-manager-de.md
  site/content/german/careers/success-manager.md
Labels: tested: OK

#362 [MRG] Swisscom Bern Bahnhof RA
  site/content/english/enable-qes.md
  site/content/english/image/map-swisscom-bern-hb-120w.jpg
  site/content/english/image/map-swisscom-bern-hb-120w.webp
  site/content/english/image/map-swisscom-bern-hb-240w.jpg
  site/content/english/image/map-swisscom-bern-hb-240w.webp
  site/content/french/enable-qes.md
  site/content/german/enable-qes.md
Labels: w/o testing

#361 [MRG] Swisscanto testimonial on index
  site/content/english/_index.md
  site/content/english/image/testimonial/swisscanto-300w.svg
  site/content/french/_index.md
  site/content/german/_index.md
Labels: w/o testing

#370 [MRG] Sales jobs - og images
  site/content/english/careers/account-executive.md
  site/content/english/careers/sales-consultant.md
  site/content/english/careers/sales-development-representative.md
  site/content/english/careers/success-manager.md
  site/content/french/careers/account-executive.md
  site/content/french/careers/sales-consultant.md
  site/content/french/careers/sales-development-representative.md
  site/content/french/careers/success-manager.md
  site/content/german/careers/account-executive.md
  site/content/german/careers/sales-consultant.md
  site/content/german/careers/sales-development-representative.md
  site/content/german/careers/success-manager.md
Labels: w/o testing

#387 [MRG] feat(corporate branding): Add testing logos for wave
  site/static/ext/branding/biz-testing-data/docusign.png
  site/static/ext/branding/biz-testing-data/ghostbusters.png
  site/static/ext/branding/biz-testing-data/python.svg
  site/static/ext/branding/biz-testing-data/star-wars-coffee.jpg
  site/static/ext/branding/biz-testing-data/troy-lee-designs.png
  site/static/ext/branding/biz-testing-data/wayne-enterprises.jpg
  site/static/ext/branding/biz-testing-data/zelda.png
Labels: w/o testing

#374 [MRG] Change to SIE: hr
  site/content/german/hr.md
Labels: tested: OK

#386 [MRG] Change to SIE: aes for business_index
  site/content/german/identifikation/aes-for-business/index.md
Labels: tested: OK

#385 [MRG] Change to SIE: features
  site/content/german/features.md
Labels: tested: OK

#384 [MRG] Change to SIE: footer
  site/config.yaml
Labels: tested: OK

#383 [MRG] Change to SIE: signaturestandards
  site/content/german/signaturestandards.md
Labels: tested: OK

#379 [MRG] Change to SIE: press room
  site/content/german/press-room.md
Labels: tested: OK

#378 [MRG] Change to SIE: lawyer
  site/content/german/lawyer.md
Labels: tested: OK

#382 [MRG] Change to SIE: sav-fsa
  site/content/german/sav-fsa.md
Labels: tested: OK

#381 [MRG] Change to SIE: qes-validator
  site/content/german/qes-validator.md
Labels: tested: OK

#377 [MRG] Change to SIE: integration
  site/content/german/integration.md
Labels: tested: OK

#380 [MRG] Change to SIE: price
  site/content/german/price.md
Labels: tested: OK

#376 [MRG] Change to SIE: increase-legal-weight
  site/content/german/increase-legal-weight.md
Labels: tested: OK

#375 [MRG] Change to SIE: identification
  site/content/german/identification.md
Labels: tested: OK

#372 [MRG] Change to SIE: index, about, enable-qes, expert-suisse, features-business
  site/content/english/image/skribble-biz-ui-de-1020w.jpg
  site/content/english/image/skribble-biz-ui-de-1020w.webp
  site/content/english/image/skribble-biz-ui-de-2040w.jpg
  site/content/english/image/skribble-biz-ui-de-2040w.webp
  site/content/english/image/skribble-biz-ui-en-1020w.jpg
  site/content/english/image/skribble-biz-ui-en-1020w.webp
  site/content/english/image/skribble-biz-ui-en-2040w.jpg
  site/content/english/image/skribble-biz-ui-en-2040w.webp
  site/content/english/image/skribble-biz-ui-fr-1020w.jpg
  site/content/english/image/skribble-biz-ui-fr-1020w.webp
  site/content/english/image/skribble-biz-ui-fr-2040w.jpg
  site/content/english/image/skribble-biz-ui-fr-2040w.webp
  site/content/english/image/skribble-ui-de-1020w.jpg
  site/content/english/image/skribble-ui-de-1020w.webp
  site/content/english/image/skribble-ui-de-2040w.jpg
  site/content/english/image/skribble-ui-de-2040w.webp
  site/content/english/image/skribble-ui-en-1020w.jpg
  site/content/english/image/skribble-ui-en-1020w.webp
  site/content/english/image/skribble-ui-en-2040w.jpg
  site/content/english/image/skribble-ui-en-2040w.webp
  site/content/english/image/skribble-ui-fr-1020w.jpg
  site/content/english/image/skribble-ui-fr-1020w.webp
  site/content/english/image/skribble-ui-fr-2040w.jpg
  site/content/english/image/skribble-ui-fr-2040w.webp
  site/content/german/_index.md
  site/content/german/about.md
  site/content/german/enable-qes.md
  site/content/german/expert-suisse.md
  site/content/german/features-business.md
Labels: tested: OK

#388 [MRG] Sub-nav and job-function
  site/config.yaml
  site/content/english/increase-legal-weight.md
  site/content/english/team.md
  site/content/french/increase-legal-weight.md
  site/content/french/team.md
  site/content/german/increase-legal-weight.md
  site/content/german/team.md
Labels: tested: OK, w/o testing
